services:
  mongo_1:
    build:
      context: .
      dockerfile: mongo.Dockerfile
    image: custom_mongo:latest
    command: ["--config", "/etc/mongo/mongod.conf", "--port", "27020"]
    container_name: mongo_node1
    hostname: mongo_node1
    volumes:
      - mongo1_data:/data/db
    user: "999:999"
    networks:
      - mongonet
    ports:
      - "27020:27020"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd!
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 2s
      retries: 5

  mongo_2:
    image: custom_mongo:latest
    command: ["--config", "/etc/mongo/mongod.conf", "--port", "27021"]
    depends_on:
      - mongo_1
    container_name: mongo_node2
    hostname: mongo_node2
    volumes:
      - mongo2_data:/data/db
    user: "999:999"
    networks:
      - mongonet
    ports:
      - "27021:27021"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd!
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27021", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 2s
      retries: 5

  mongo_3:
    image: custom_mongo:latest
    command: ["--config", "/etc/mongo/mongod.conf", "--port", "27022"]
    depends_on:
      - mongo_1
    container_name: mongo_node3
    hostname: mongo_node3
    volumes:
      - mongo3_data:/data/db
    user: "999:999"
    networks:
      - mongonet
    ports:
      - "27022:27022"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd!
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27022", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 2s
      retries: 5

  mongo_init:
    build: .
    image: custom_mongo:latest
    hostname: mongo_init
    container_name: mongo_init
    networks:
      - mongonet
    depends_on:
      mongo_1:
        condition: service_healthy
      mongo_2:
        condition: service_healthy
      mongo_3:
        condition: service_healthy
    command: >
      mongosh --host mongo_node1:27020 --username admin --password P@ssw0rd! --authenticationDatabase admin --eval
      '
      rs.initiate(
        {
          "_id": "pasReplicaSet",
          "members": [
            { _id: 0, host : "mongo_node1:27020" },
            { _id: 1, host : "mongo_node2:27021" },
            { _id: 2, host : "mongo_node3:27022" }
          ]
        }
      );
      '

volumes:
  mongo1_data:
    driver: local
  mongo2_data:
    driver: local
  mongo3_data:
    driver: local

networks:
  mongonet:
    driver: bridge